spring:
  application:
    name: echonexus-api-gateway
  cloud:
    gateway:
      routes:
        - id: v1-echonexus-api-clients
          uri: ${API_V1_BASE_URI}
          predicates:
            - Path=/v1/clients/**
          filters:
            - SupabaseJwtParser=
            - ClientSubdomainParser=
            - SetResponseHeader=Content-Type, application/json
        - id: v1-echonexus-api-issues
          uri: ${API_V1_BASE_URI}
          predicates:
            - Path=/v1/issues/**
          filters:
            - SupabaseJwtParser=
            - ClientSubdomainParser=
            - SetResponseHeader=Content-Type, application/json
        - id: v1-echonexus-api-payments-public
          uri: ${API_V1_BASE_URI}
          predicates:
            Path=/v1/payments/plans
          filters:
            - ClientSubdomainParser=
            - SetResponseHeader=Content-Type, application/json
        - id: v1-echonexus-api-projects
          uri: ${API_V1_BASE_URI}
          predicates:
            - Path=/v1/projects/**
          filters:
            - SupabaseJwtParser=
            - ClientSubdomainParser=
            - SetResponseHeader=Content-Type, application/json
        - id: v1-echonexus-api-products-feedback
          uri: ${API_V1_BASE_URI}
          predicates:
            - Path=/v1/products/feedback/**
          filters:
            - ClientSubdomainParser=
            - SetResponseHeader=Content-Type, application/json
        - id: v1-echonexus-api-users
          uri: ${API_V1_BASE_URI}
          predicates:
            - Path=/v1/users/**
          filters:
            - SupabaseJwtParser=
            - ClientSubdomainParser=
            - SetResponseHeader=Content-Type, application/json
        - id: v1-echonexus-scripts
          uri: ${API_V1_BASE_URI}
          predicates:
            - Path=/v1/scripts/**
          filters:
            - ClientSubdomainParser=
            - SetResponseHeader=Content-Type, text/javascript; charset=utf-8
  webflux:
    static-path-pattern: /v1/scripts/**
supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET}
echonexus:
  cors:
    origin: ${FRONT_END_URL}
